using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinhVienConnectDB.Models
{
    [global::System.Data.Linq.Mapping.DatabaseAttribute(Name = "64PM12")]
    public partial class DatabaseDataContext : System.Data.Linq.DataContext
    {

        private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();

        #region Extensibility Method Definitions
        partial void OnCreated();
        partial void Inserttbl_SinhVien(tbl_SinhVien instance);
        partial void Updatetbl_SinhVien(tbl_SinhVien instance);
        partial void Deletetbl_SinhVien(tbl_SinhVien instance);
        #endregion

        public DatabaseDataContext() :
                base(global::SinhVienConnectDB.Properties.Settings.Default._64PM12ConnectionString, mappingSource)
        {
            OnCreated();
        }

        public DatabaseDataContext(string connection) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public DatabaseDataContext(System.Data.IDbConnection connection) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
                base(connection, mappingSource)
        {
            OnCreated();
        }

        public System.Data.Linq.Table<tbl_SinhVien> tbl_SinhViens
        {
            get
            {
                return this.GetTable<tbl_SinhVien>();
            }
        }
    }

    [global::System.Data.Linq.Mapping.TableAttribute(Name = "dbo.tbl_SinhVien")]
    public partial class tbl_SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private string _ID;

        private string _MSSV;

        private string _HoTen;

        private System.Nullable<System.DateTime> _NgaySinh;

        private string _GioiTinh;

        private string _DiaChi;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnIDChanging(string value);
        partial void OnIDChanged();
        partial void OnMSSVChanging(string value);
        partial void OnMSSVChanged();
        partial void OnHoTenChanging(string value);
        partial void OnHoTenChanged();
        partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
        partial void OnNgaySinhChanged();
        partial void OnGioiTinhChanging(string value);
        partial void OnGioiTinhChanged();
        partial void OnDiaChiChanging(string value);
        partial void OnDiaChiChanged();
        #endregion

        public tbl_SinhVien()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_ID", DbType = "NVarChar(20) NOT NULL", CanBeNull = false, IsPrimaryKey = true)]
        public string ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                if ((this._ID != value))
                {
                    this.OnIDChanging(value);
                    this.SendPropertyChanging();
                    this._ID = value;
                    this.SendPropertyChanged("ID");
                    this.OnIDChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_MSSV", DbType = "NVarChar(20) NOT NULL", CanBeNull = false)]
        public string MSSV
        {
            get
            {
                return this._MSSV;
            }
            set
            {
                if ((this._MSSV != value))
                {
                    this.OnMSSVChanging(value);
                    this.SendPropertyChanging();
                    this._MSSV = value;
                    this.SendPropertyChanged("MSSV");
                    this.OnMSSVChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_HoTen", DbType = "NVarChar(200) NOT NULL", CanBeNull = false)]
        public string HoTen
        {
            get
            {
                return this._HoTen;
            }
            set
            {
                if ((this._HoTen != value))
                {
                    this.OnHoTenChanging(value);
                    this.SendPropertyChanging();
                    this._HoTen = value;
                    this.SendPropertyChanged("HoTen");
                    this.OnHoTenChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_NgaySinh", DbType = "Date")]
        public System.Nullable<System.DateTime> NgaySinh
        {
            get
            {
                return this._NgaySinh;
            }
            set
            {
                if ((this._NgaySinh != value))
                {
                    this.OnNgaySinhChanging(value);
                    this.SendPropertyChanging();
                    this._NgaySinh = value;
                    this.SendPropertyChanged("NgaySinh");
                    this.OnNgaySinhChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_GioiTinh", DbType = "NVarChar(5)")]
        public string GioiTinh
        {
            get
            {
                return this._GioiTinh;
            }
            set
            {
                if ((this._GioiTinh != value))
                {
                    this.OnGioiTinhChanging(value);
                    this.SendPropertyChanging();
                    this._GioiTinh = value;
                    this.SendPropertyChanged("GioiTinh");
                    this.OnGioiTinhChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_DiaChi", DbType = "NText", UpdateCheck = UpdateCheck.Never)]
        public string DiaChi
        {
            get
            {
                return this._DiaChi;
            }
            set
            {
                if ((this._DiaChi != value))
                {
                    this.OnDiaChiChanging(value);
                    this.SendPropertyChanging();
                    this._DiaChi = value;
                    this.SendPropertyChanged("DiaChi");
                    this.OnDiaChiChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
#pragma warning restore 1591
